CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    phone VARCHAR(20),
    role VARCHAR(20) NOT NULL,
    credit INT NOT NULL DEFAULT 100,
    status VARCHAR(20) NOT NULL DEFAULT 'normal',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS user_address (
    address_id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    receiver_name VARCHAR(50) NOT NULL,
    receiver_phone VARCHAR(20) NOT NULL,
    detail_address VARCHAR(500) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (address_id)
);

CREATE TABLE IF NOT EXISTS user_realname_auth (
    id BIGINT NOT NULL AUTO_INCREMENT, user_id BIGINT NOT NULL, real_name VARCHAR(50) NOT NULL,
    id_card_masked VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS credit_record (
    id BIGINT NOT NULL AUTO_INCREMENT, user_id BIGINT NOT NULL, change_value INT NOT NULL,
    reason VARCHAR(255) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id)
);
