CREATE TABLE IF NOT EXISTS goods (
    goods_id BIGINT NOT NULL AUTO_INCREMENT,
    seller_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ON_SALE',
    sold_order_number VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (goods_id)
);

CREATE TABLE IF NOT EXISTS store (
    store_id BIGINT NOT NULL AUTO_INCREMENT, seller_id BIGINT NOT NULL, store_name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'normal', PRIMARY KEY (store_id)
);

CREATE TABLE IF NOT EXISTS favorite_goods (
    id BIGINT NOT NULL AUTO_INCREMENT, user_id BIGINT NOT NULL, goods_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE (user_id, goods_id)
);

CREATE TABLE IF NOT EXISTS browse_history (
    id BIGINT NOT NULL AUTO_INCREMENT, user_id BIGINT NOT NULL, goods_id BIGINT NOT NULL,
    viewed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS follow_store (
    id BIGINT NOT NULL AUTO_INCREMENT, user_id BIGINT NOT NULL, store_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE (user_id, store_id)
);
